from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about-us/", views.about, name="about"),
    path("markets/", views.market, name="market"),
    path("blog/", views.blog, name="blog"),
    path("team/", views.team, name="team"),
    path("bitcoin/", views.bit_coin, name="bitcoin"),
    path("esg/", views.esg, name="esg"),
    path("finance/", views.finance, name="finance"),
    path("private-wealth/", views.private_wealth, name="private_wealth"),
    path("estate-planning/", views.estate_planing, name="estate_planing"),
    path("long-term-care/", views.long_term_care, name="long_term_care"),
    path("business-planning/", views.business_planning, name="business_planning"),
    path("oil-gas/", views.oil_gas, name="oil_gas"),
    path("help-center/", views.help_center, name="help_center"),
    path("testimonies/", views.testimonies, name="testimonies"),
    path("legal-docs/", views.legal_docs, name="legal_docs"),
    path("terms/", views.terms, name="terms"),
    path("policies/", views.policies, name="policies"),
    path("insurance/", views.insurance, name="insurance"),
    path("criminal-activity/", views.criminal_activity, name="criminal_activity"),
    path("cashback/", views.cashback, name="cashback"),
    path("disclamer/", views.disclamer, name="disclamer"),
    path("license/", views.license, name="license"),
    path("stocks/", views.stocks, name="stocks"),
    path("forex/", views.forex, name="forex"),
    path("real-estate/", views.real_estate, name="real_estate"),
    path("crypto/", views.crypto, name="crypto"),
    path("fixed-income/", views.fixed_income, name="fixed_income"),
    path("agric-investment/", views.agric_investment, name="agric_investment"),
    path("renewable-power/", views.renewable_power, name="renewable_power"),
    path("nfp/", views.nfp, name="nfp"),
    path("multi-assets/", views.multi_assets, name="multi_assets"),
    path("infrastructure/", views.infrastructure, name="infrastructure"),
    path("philosophy/", views.philosophy, name="philosophy"),
]
